- name: Include OS-Specific variables
  include_vars: main.yml 

- include: validate.yml
  tags: 
    - install-grafana
   
- include: Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - install-grafana

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - install-grafana

# Configure grafana init settings.
- include: settings.yml
  tags:
    - install-grafana
