- include: validate.yml
  tags:
    - install-grafana

- include: Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - install-grafana

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - install-grafana

# Configure grafana init settings.
- include: settings.yml
  tags:
    - install-grafana
