- name: RedHat | Add Grafana repository
  yum_repository:
    name: "{{ rh.grafana_repo_name }}"
    description: "{{ rh.grafana_repo_description }}"
    baseurl: "{{ rh.grafana_repo_url }}"
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: "{{ rh.grafana_repo_key_url }}"

- name: RedHat | Install grafana
  package:
    name: grafana
    state: present
  notify:
    - RedHat | init grafana service
# firewalld is inactive by default on redhat disctributions
- name: RedHat | Enable firewalld
  service: 
    name: firewalld
    state: started
    enabled: yes
    
- name: RedHat | Allow grafana port 
  command: firewall-cmd --permanent --zone=public --add-port=3000/tcp
  notify: 
    - RedHat | restart firewalld service
    - start grafana service
