- name: RedHat | Add Grafana repository
  yum_repository:
    name: "{{ rh.grafana_repo_name }}"
    description: "{{ rh.grafana_repo_description }}"
    baseurl: "{{ rh.grafana_repo_url }}"
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: "{{ rh.grafana_repo_key_url }}"
    sslverify: yes
    sslcacert: "{{ rh.sslcacert_file }}"

- name: RedHat | Install grafana
  yum:
    name: grafana
    state: installed
    update_cache: yes
  notify:
    - RedHat | init grafana service redhat
# firewalld is inactive by default on redhat disctributions
- name: RedHat | Enable firewalld
  service: 
    name: firewalld
    state: started
    enabled: yes
    
- name: RedHat | Allow grafana port 
  command: firewall-cmd --permanent --zone=public --add-port=3000/tcp
  notify: 
    - restart firewalld
    - start grafana
